/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ExploreContainer: typeof import('./src/components/ExploreContainer.vue')['default']
    LiteTabs: typeof import('./src/components/liteTabs.vue')['default']
    Robot: typeof import('./src/components/robot.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TalkContainer: typeof import('./src/components/TalkContainer.vue')['default']
  }
}
